### ISSUE TITLE
[Feature] [Self-assigned] Add heatmap plotter

### ISSUE THREAD

**Issue by DanielYang59** [janosh/pymatviz#118]
Hi @janosh, I happen to have some plotting scripts for my MPhil research which includes plotting heatmaps. Shall I proceed and try to merge them into your package?

For example:
![headmap1](https://github.com/janosh/pymatviz/assets/80093591/4c4ad8a7-c284-4ece-ab5d-767b6e32a36a)

And this (I didn't find a good way to fix these overlapping labels though):
![heatmap2](https://github.com/janosh/pymatviz/assets/80093591/5678252c-ea80-4a70-bbdf-ff00309d1ecf)

**Comment by janosh** [comment]
Certainly, if you can turn these figures into generic reusable functions and provide the specific outputs above as usage examples in the `examples/` folder, that would be great! 👍

**Comment by DanielYang59** [comment]
@janosh Sure thanks. I would look into your existing codes and try to unify the function input/output flow. Cheers!

**Comment by janosh** [comment]
Happy to help. Feel free to open a PR early and we can iterate together.

**Comment by DanielYang59** [comment]
@janosh Thanks for offering that. However I might prefer to take my time and format the code on my own pace for the time being. I mean no offence but your energy is crazy, there is no way for me to catch up haha... Also coding is quite new to me (around only ~1 year experience) plus I'm current busy cleaning up my Journal Paper from my previous MPhil Thesis to support my future PhD position search.
