### ISSUE TITLE
New plot type: `ptable_scatter`

### ISSUE THREAD

**Issue by janosh** [janosh/pymatviz#119]
Add `ptable_scatter` equivalent to `ptable_hists`. Function signature can be largely identical except each element data must specify both x and y data. Could potentially have a single function that toggles between `hist` and `scatter` depending on presence of y data.

https://github.com/janosh/pymatviz/blob/882a6caaa06acbcadbcfc3d8e2d7fe6aa8ce630e/pymatviz/ptable.py#L745-L795

**Comment by DanielYang59** [comment]
I would be working on this. Thanks @janosh!

**Comment by janosh** [comment]
Thanks, that would be much appreciated! It can be very close in implementation to the existing ptable_hists

**Comment by DanielYang59** [comment]
I'm thinking a dedicated data type for periodic table might be justified. I'm currently unaware of any existing package (closest is [periodictable](https://github.com/pkienzle/periodictable) but doesn't seem to be designed for parsing custom datasheet).

It would be very similar to a Python dictionary, but with the keys predefined as elements (The atomic numbers should be used internally and auxiliarily for ordering) and missing values imputated.

Having this, we would be able to unify handling and parsing of multiple periodic table based plots, data for `ptable_heatmap` and `ptable_hists` would be simplified to `element: float` pairs. Then we could make fancy scatter plots easy to handle and scale up to multi-dimensional data, `ptable_scatter_2D` would be `element: [float, float]` pairs, and we could also include a 3rd dimension (either the size of the scatter or colormap) by using `element: [float, float, float]`. And this would also make 3D scatters easy to plot. What do you think?

**Comment by janosh** [comment]
not sure we need a data type to represent `PeriodicTable`. even if, i think `pymatgen` rather than `pymatviz` would be the place for it. i would prefer a helper function that converts input data in different formats (e.g. using atomic numbers vs element symbols as keys, or dictionaries vs `pd.Series` to a consistent internal format. that helper can be called inside each plotting function before the actual plotting code.

for the use case you outline of having additional dimensions for color or marker size, a `pd.DataFrame` already seems like the optimal format. you simply pass around dataframes to plotting functions along with column names to use for `x`/`y`/`color`/`marker size`. works great for `plotly`.

**Comment by DanielYang59** [comment]
Thanks for sharing your thoughts @janosh. It make sense, as `pd.DataFrame` should be able to do what I wish to do and I would use it for the time being until perhaps put a periodic table data parser to either `pymatgen` or others.

**Comment by janosh** [comment]
closed in #122
