### ISSUE TITLE
`ptable_heatmap` with diagonally-split tiles

### ISSUE THREAD

**Issue by keeganq** [janosh/pymatviz#130]
Hi, thanks for this really awesome repository! Very easy to use with satisfying results.

Are there plans to add functionality for joint periodic table plots for comparing two values?  Similar to the one shown here: https://www.nature.com/articles/s42256-023-00716-3/figures/2

Would be great to have this kind of visualization in the toolkit, as I think it's much easier than trying to compare two `ptable_heatmap` plots.

**Comment by janosh** [comment]
yeah, i almost implemented this as a reusable function at one point. don't remember why it didn't happen and unfortunately don't have time right now. but it's been on the roadmap for a while and a PR would be very welcome!

pinging @DanielYang59 just in case you'd like to work on this. no expectations of course

**Comment by DanielYang59** [comment]
Looks good. I would have a try and see how everything goes. Thanks for pinging me!

**Comment by DanielYang59** [comment]
Hi @keeganq We just added the requested plotter with #131, and please let me know if you have further suggestions on existing plotter.

To use the new plotter, you could use the following (basically just pass a `{element_name: [*values]}` dict to the plotter):
https://github.com/janosh/pymatviz/blob/492cd5301f9b241291a49f24a4d8adbbd50ae5c6/examples/_generate_assets.py#L218-L232

**Comment by keeganq** [comment]
This is awesome, @DanielYang59. Thank you!

**Comment by DanielYang59** [comment]
No worries at all. This can never be done so well without @janosh's suggestions. 

Meanwhile we're trying to improve the API for ptable plotters, so if you have any comments/suggestions during usage, please let me know. That would be valuable feedback for me.
