### ISSUE TITLE
Legacy `eslint` config file deprecated and caused `pre-commit` to fail

### ISSUE THREAD

**Issue by DanielYang59** [janosh/pymatviz#136]
### Pre-commit `eslint` config file outdated 

Failed both on my local machine and [CI](https://results.pre-commit.ci/run/github/340898532/1713960833.Pl3yBHPYQgiDaBd4dfbpTA). 

https://github.com/eslint/eslint/issues/18350 points to a deprecated `.eslintrc.yml` file in v9.0.0 afterwards. I added an environment variable `ESLINT_USE_FLAT_CONFIG=false` in e8669fba0b7bc740c48cf821aaddf097b6376b5f to allow usage of the legacy config file for now. But it's certainly better to migrate to the new config file ([legacy config file support would be removed completely in v10](https://github.com/eslint/eslint/issues/18350#issuecomment-2058524220) ).

**Comment by janosh** [comment]
have a look at [janosh/matbench-discovery/commit/a3b43624b](https://github.com/janosh/matbench-discovery/commit/a3b43624b5bba0562bdbf5b0fb9fc15cefb8ffbe#diff-09727da4ae7240fbadc8e8ff273ebe1c0229731dcd803fb715a84089cd636bc2) which already migrated to flat `eslint` config, i.e. avoiding the need for `ESLINT_USE_FLAT_CONFIG=false`.
