### ISSUE TITLE
Several possible improvements for `ptable_heatmap` plotter

### ISSUE THREAD

**Issue by DanielYang59** [janosh/pymatviz#138]
I noticed several minor issues with `ptable_heatmap` plotter:
- The font style of the text in each tile and colorbar title cannot be controlled individually (only a single `text_style` arg is allowed). (Maybe the new implementation would fix this automatically because they would be separate objects then)
- The colormap is named as `colorscale`, maybe rename it to `colormap` for consistency with `matplotlib` and other parts of the code?
- The default setting doesn't format numbers in (-1, 1) range well, see the below example (data for Ag and Zn is 0.93 and -0.43). Manually set `fmt` fixes the issue though.

  ![test_plot](https://github.com/janosh/pymatviz/assets/80093591/b476c9ff-ee84-452a-87c7-9ed6cabc3134)

- Should we add an option to allow easy hiding of the Lanthanum and Actinium series (maybe there is already one that I'm not aware of)?

**Comment by janosh** [comment]
thanks! all great suggestions. 👍 

> The colormap is named as colorscale, maybe rename it to colormap for consistency with matplotlib and other parts of the code?

it used to be `colormap` but at some point i renamed to `colorscale` with `ptable_heatmap_plotly`. `plotly` and `matplotlib` have differing terminology here. i'm leaning towards keeping `colorscale` but happy to hear other views.

> The default setting doesn't format numbers in (0, 1) range well, see the below example (data for Ag and Zn is 0.93 and -0.43). Manually set fmt fixes the issue though.

thanks for reporting, that's terrible default behavior!

> Should we add an option to allow easy hiding of the Lanthanum and Actinium series (maybe there is already one that I'm not aware of)?

let's do it!

**Comment by DanielYang59** [comment]
> > The colormap is named as colorscale, maybe rename it to colormap for consistency with matplotlib and other parts of the code?
> 
> it used to be `colormap` but at some point i renamed to `colorscale` with `ptable_heatmap_plotly`. `plotly` and `matplotlib` have differing terminology here. i'm leaning towards keeping `colorscale` but happy to hear other views.

Thanks for the input. I'm not quite sure either. Let's keep it as is for now.

> > Should we add an option to allow easy hiding of the Lanthanum and Actinium series (maybe there is already one that I'm not aware of)?
> 
> let's do it!

I would push a PR to add this soon :)

**Comment by janosh** [comment]
i think "impute" is being misused here. it usually means inferring a likely value from context/experience. not sure what you mean by "zero: impute with zeros"

https://github.com/janosh/pymatviz/blob/492cd5301f9b241291a49f24a4d8adbbd50ae5c6/pymatviz/ptable.py#L310-L315

**Comment by DanielYang59** [comment]
Thanks for bringing this up. I used the word "impute" just like the [`scikit-learn` documents does](https://scikit-learn.org/stable/modules/impute.html) (maybe I misunderstood):
> A better strategy is to impute the missing values, i.e., to infer them from the known part of the data. See the glossary entry on [imputation](https://scikit-learn.org/stable/glossary.html#term-imputation).

> One type of imputation algorithm is univariate, which imputes values in the i-th feature dimension using only non-missing values in that feature dimension (e.g. [SimpleImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer)). By contrast, multivariate imputation algorithms use the entire set of available feature dimensions to estimate the missing values (e.g. [IterativeImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.IterativeImputer.html#sklearn.impute.IterativeImputer)).
