### ISSUE TITLE
`ptable_heatmap_splits` raises unexpected `TypeErrors`

### ISSUE THREAD

**Issue by janosh** [janosh/pymatviz#145]
@DanielYang59 i noticed a few bugs in `ptable_heatmap_splits`

```py
ptable_heatmap_splits({"H": [1, 2]})
>>> TypeError: 'NoneType' object is not callable
```

you need to explicitly pass a `colormap` to avoid this. we should set a default. also:
```py
ptable_heatmap_splits({"H": {"A": 1, "B": 2}.values()}, colormap="RdBu_r")
>>> TypeError: Unsupported data type.
```

we currently don't handle type [`dict_values`](https://docs.python.org/3/c-api/dict.html#c.PyDict_Values). if you wrap `dict_values` in `list`, it works:

```py
ptable_heatmap_splits({"H": list({"A": 1, "B": 2}.values())}, colormap="RdBu_r")
```

**Comment by DanielYang59** [comment]
Thanks for reporting. I don't even know why `colormap` is default as `None` to start with (because `None` would not work as a valid `colormap`), must be a huge oversight from my sight.
