### ISSUE TITLE
Add `density_scatter_plotly`

### ISSUE THREAD

**Issue by janosh** [janosh/pymatviz#160]
one very important plot type that i've been meaning to port over to `pymatviz` is a truly scalable version of `density_scatter` but using `plotly` as backend to get interactive tooltips. those can be very useful when making parity plots of e.g. of [machine learning models tested on large datasets](https://matbench-discovery.materialsproject.org/preprint#parity-plots):

![Screenshot 2024-06-17 at 21 09 39](https://github.com/janosh/pymatviz/assets/30958850/c16cefb7-150f-4219-872e-66fa14c075a8)

`density_scatter` could either be upgraded by adding a `backend="plotly"` option or by making a new plot function `density_scatter_plotly`. i prefer the 1st option from a user-facing API perspective but think the code would end up more readable taking the 2nd option. still, option 1 probably better.

given [matbench discovery already has several examples](https://github.com/search?q=repo%3Ajanosh%2Fmatbench-discovery%20bin_df_cols&type=code) of how to make such plots, it would largely be a case of wrapping [the way `bin_df_cols` is used here](https://github.com/janosh/matbench-discovery/blob/b10e608f5c0d3bec6f77097dcd84e5e2f11b4a58/scripts/model_figs/parity_energy_models.py#L61-L95) into a more streamlined user-friendly function.

**Comment by DanielYang59** [comment]
Certainly. But shall we finish #157 before this (one thing at a time)? I'm currently taking some time off, and would get my hands on #157 very soon :)

> density_scatter could either be upgraded by adding a backend="plotly" option or by making a new plot function density_scatter_plotly. i prefer the 1st option from a user-facing API perspective but think the code would end up more readable taking the 2nd option. still, option 1 probably better.

I don't have extensive experience with `plotly`, if it shares most grammar with `matplotlib`, 1st option might be preferred. If not, I would personally prefer 2nd (the `ptable_heatmap_plotly` for example). Also the 2nd option might be useful if we were to separate `pymatviz` into `matplotlib` and `plotly` at some point (i.e. static plotters and interactive plotters)?

**Comment by janosh** [comment]
> But shall we finish https://github.com/janosh/pymatviz/pull/157 before this (one thing at a time)?

i think those PR shouldn't cause merge conflicts since they touch different files. unless you're worried about context switching? that's a valid point.

> I don't have extensive experience with plotly, if it shares most grammar with matplotlib, 1st option might be preferred.

`plotly` and `matplotlib` syntax is entirely different. i actually prefer `plotly`'s syntax. it's more consistent across figure types and therefore easier to learn. [NOMAD makes extensive use of `plotly` as well](https://gitlab.mpcdf.mpg.de/search?search=plotly&nav_source=navbar&project_id=2187&group_id=27&search_code=true&repository_ref=develop).

> Also the 2nd option might be useful if we were to separate pymatviz into matplotlib and plotly at some point (i.e. static plotters and interactive plotters)?

i wasn't planning on that but of course i'm open to arguments

**Comment by DanielYang59** [comment]
> > But shall we finish #157 before this (one thing at a time)?
> 
> i think those PR shouldn't cause merge conflicts since they touch different files. unless you're worried about context switching? that's a valid point.

Yep I want to focus one thing at a time. Because I could see quite some work coming for the heatmap plotter refactor :)

> > I don't have extensive experience with plotly, if it shares most grammar with matplotlib, 1st option might be preferred.
> 
> `plotly` and `matplotlib` syntax is entirely different. i actually prefer `plotly`'s syntax. it's more consistent across figure types and therefore easier to learn. [NOMAD makes extensive use of `plotly` as well](https://gitlab.mpcdf.mpg.de/search?search=plotly&nav_source=navbar&project_id=2187&group_id=27&search_code=true&repository_ref=develop).

Thanks for letting me know. I really want to learn something about `plotly` from this collaboration :)

> > Also the 2nd option might be useful if we were to separate pymatviz into matplotlib and plotly at some point (i.e. static plotters and interactive plotters)?
> 
> i wasn't planning on that but of course i'm open to arguments

I wasn't suggesting this even for the near future, I would assume it's something we might consider when `pymatviz` gets really large :)
