### ISSUE TITLE
[Dev] GitHub Pages- Build site workflow is failing

### ISSUE THREAD

**Issue by DanielYang59** [janosh/pymatviz#181]
[GitHub Pages- Build site workflow is failing](https://github.com/janosh/pymatviz/actions/runs/9999554172/job/27654818374). Looks like the same as https://github.com/npm/cli/issues/7666.

Just guess, not sure, perhaps we should limit the version to 22.4 https://github.com/npm/cli/issues/7666#issuecomment-2238552112:
https://github.com/janosh/workflows/blob/a03fa54b611812dc710460abe6ad69ddec4984bc/.github/workflows/nodejs-gh-pages.yml#L6-L9

**Comment by DanielYang59** [comment]
For some reason [NodeJS is still version 22.5.0](https://github.com/janosh/pymatviz/actions/runs/9999554172/job/27664776780)? Meanwhile don't know where the following error come from (why `cssutils` is needed to build docs)?

```
Failed to generate docs for module io: ModuleNotFoundError("No module named 'cssutils'")
```

**Comment by janosh** [comment]
> For some reason [NodeJS is still version 22.5.0](https://github.com/janosh/pymatviz/actions/runs/9999554172/job/27664776780) (perhaps the workflow need some time to update?)?

not to worry, pretty sure that's just because i reran a workflow that triggered before this PR was merged and so it seems to have used the same commit SHA it ran with the 1st time, i.e. with the code before this PR
