### ISSUE TITLE
Restore `ptable_hists` kwarg `anno_kwds` (or something similar)

### ISSUE THREAD

**Issue by janosh** [janosh/pymatviz#199]
@DanielYang59 re [your comment](https://github.com/janosh/pymatviz/pull/149/files#r1613192588)

> Previously the `ptable_hists` has `symbol_kwargs` and `anno_kwds`. In the new implementation, support for annotate is completely removed, as I would assume their functionality overlaps.

i just realized that the removal of `anno_kwds` caused some issues over in [`matbench-discovery/data/mp/eda_mp_trj.py#L162`](https://github.com/janosh/matbench-discovery/blob/594db5fcde37d8e1dd14371a906bb96f4e41c0a0/data/mp/eda_mp_trj.py#L162) as mentioned in https://github.com/janosh/matbench-discovery/pull/130#discussion_r1733749688. do you remember what you meant by `symbol_kwargs` overlaps with `anno_kwds`. i don't think one can replace the other. this is the output with and without `anno_kwds`. maybe in this case the figure is overplotted with those histogram count annotations but in principle, i think the feature is nice to have (though perhaps with a better name)

![Screenshot 2024-09-05 at 16 29 26](https://github.com/user-attachments/assets/03180d69-8232-442f-8834-9de71c783a21)

**Comment by DanielYang59** [comment]
> do you remember what you meant by `symbol_kwargs` overlaps with `anno_kwds`. i don't think one can replace the other. 

Ah okay. I originally thought there would not be a use case where one need to add additional text (`annotate`)
 on top of the chemical symbol (because the nested histogram, and other nested plot in general, has been quite informative already). But looks like that is a valid use case, so let's add it back :)
