### ISSUE TITLE
Tests are included in source distribution?

### ISSUE THREAD

**Issue by DanielYang59** [janosh/pymatviz#201]
- I noticed [tests are included in source distribution](https://pypi.org/project/pymatviz/#files) not wheels, is it deliberate?
  ```
  .......
  drwxr-xr-x  0 janosh wheel       0 Sep  1 13:37 pymatviz-0.11.0/tests/
  -rw-r--r--  0 janosh wheel    2061 Aug 22 19:34 pymatviz-0.11.0/tests/test_bar.py
  -rw-r--r--  0 janosh wheel     507 Aug 22 14:25 pymatviz-0.11.0/tests/test_correlation.py
  -rw-r--r--  0 janosh wheel     716 Aug 22 19:35 pymatviz-0.11.0/tests/test_cumulative.py
  -rw-r--r--  0 janosh wheel    2873 Jul 28 04:08 pymatviz-0.11.0/tests/test_enums.py
  -rw-r--r--  0 janosh wheel    2419 Aug 22 19:34 pymatviz-0.11.0/tests/test_histogram.py
  ......
  ```
- The wheel build target seems to include Python 2: `pymatviz-0.11.0-py2.py3-none-any.whl `
    <img width="531" alt="image" src="https://github.com/user-attachments/assets/dee9e4c8-608a-475d-9dac-1996965703f4">

**Comment by janosh** [comment]
thanks for opening an issue to track this! 👍 that is not intended. i noticed this too and tried to fix but didn't manage. this line is meant to exclude tests but doesn't have the intended effect.

https://github.com/janosh/pymatviz/blob/24261caea8af69ab9698308ce6034bd8ca67b3c1/pyproject.toml#L58

i tried a few different configs but none worked. any ideas appreciated! that said, afaik some people argue source distributions _should_ include the test files. but i'm leaning more towards excluding them.

**Comment by janosh** [comment]
> The wheel build target seems to include Python 2: pymatviz-0.11.0-py2.py3-none-any.whl 

i wasn't aware of that. that's also not intended. i wonder what effect this line has. apparently none?

https://github.com/janosh/pymatviz/blob/24261caea8af69ab9698308ce6034bd8ca67b3c1/pyproject.toml#L19

**Comment by DanielYang59** [comment]
> thanks for opening an issue to track this! 👍 that is not intended. i noticed this too and tried to fix but didn't manage. this line is meant to exclude tests but doesn't have the intended effect.
> 
> https://github.com/janosh/pymatviz/blob/24261caea8af69ab9698308ce6034bd8ca67b3c1/pyproject.toml#L58

Ah okay! Thanks for the input. The reason is also a bit unclear to me (I don't quite understand why the tests are only in sdist not bdist), I would investigate and let you know if I find anything.


>  some people argue source distributions _should_ include the test files. but i'm leaning more towards excluding them.

I think some people would consider tests a part of their code base for testing deployment or something.

**Comment by janosh** [comment]
in principle it [should happen here](https://github.com/janosh/workflows/blob/2bef95635c12241f8eac35d9b09061ddd038a757/.github/workflows/pytest-release.yml#L81-L87) except PyPI trusted publishing doesn't support GitHub reusable workflows atm (see https://github.com/pypa/gh-action-pypi-publish/issues/166). so for now i run an equivalent command locally to publish to PyPI

```sh
python -m build
twine upload --verbose --skip-existing dist/*
```

**Comment by DanielYang59** [comment]
Thanks for the input, I could recreate this, would look into it!

```
python3 -m build --wheel
>>> Successfully built pymatviz-0.11.0-py2.py3-none-any.whl
```
