### ISSUE TITLE
behavior change in `ptable_heatmap_ratio` 

### ISSUE THREAD

**Issue by DanielYang59** [janosh/pymatviz#215]
Unexpected behavior change in `ptable_heatmap_ratio`, some blue tiles (not in 2nd tile) now becomes grey (not in 1nd tile)

![ptable-heatmap-ratio](https://github.com/user-attachments/assets/a5af4420-bb95-4fd2-ad2e-3cb8271d6407)

`0.10.0` seems to work correctly, but `0.10.1` is broken.

**Comment by janosh** [comment]
good thing you noticed! no idea what might have caused this

**Comment by DanielYang59** [comment]
I haven't investigated yet, but I will later :)
