### ISSUE TITLE
Split `make_assets` scripts by plot function

### ISSUE THREAD

**Issue by janosh** [janosh/pymatviz#245]
Currently, `make_assets` scripts are named after the file whose plot function they import and demo. i think it would be better to split those scripts into one demo file per plot function. would make it easier to check that each plot function has at least 2 or 3 examples. it would also allow linking from the readme table directly to the examples we have for each function. right now, the readme table instead links to the source code which is less helpful

@DanielYang59 is this something you're interested in?

**Comment by DanielYang59** [comment]
Sure I would do that (was looking into the asset maker seconds ago for the isotopes in `pymatgen` `Element` which I mentioned in one comment somewhere, https://github.com/materialsproject/pymatgen/discussions/4178). That would make assert maker much easier to access (I was having a hard time trying to find the corresponding assert maker almost every time).

**Comment by DanielYang59** [comment]
And I was thinking about this seconds before you opened this issue: what about moving `make_assets` under `assets` instead of `examples` as we're linking to it anyway.

I found myself going to `asset` directory to look for the script almost every time 🙈

**Comment by janosh** [comment]
> what about moving make_assets under assets instead of examples as we're linking to it anyway.

i view them more for the user's benefit than purely as dev code which is why i put them in `examples/` originally. that said, i suppose it would be more useful to users if they were jupyter notebooks with the generated figures displayed inline which makes much easier to associate code with output. we could put the scripts in `assets/` and convert them to notebooks for the docs site on the fly

**Comment by DanielYang59** [comment]
Yes that's the reason I propose this here, after we link those examples figures to their own asset makers, we could now relocate scripts under `asset/` without worry about discoverability.
