### ISSUE TITLE
`plot_structure_2d()` show bonds

### ISSUE THREAD

**Issue by sgbaird** [janosh/pymatviz#38]
Had a random thought. As I was looking through some of the images, I notice that it's difficult to get a sense of the depth and by extension the relative distances between things. Perhaps semi-transparent "tubes" that vary in size based on the bond distance would help. Or maybe that's something that's better suited for visualization via VESTA. Thinking about using `plot_structure_2d` extensively for an upcoming manuscript.

No pressure - just a random passing thought.

**Comment by janosh** [comment]
I'm thinking it might be more useful to go straight for 3d visualization. We could have a function that takes pymatgen structures and converts them into the `xyz` format used by https://github.com/wwwtyro/speck which is available in Plotly's [`dash-bio`](https://dash.plotly.com/dash-bio/speck`) package.

Would look something like this (subject to further customization).

![Screen Shot 2022-05-22 at 09 02 47](https://user-images.githubusercontent.com/30958850/169685031-2c25c7f3-f056-476d-8e77-36a462bab94f.png)

You can't really tell the periodic structure from this though. We'd want to include box edges to indicate the unit cell (which might take some work) and plot the conventional cell to make it look more like https://materialsproject.org/materials/mp-19017.
