### ISSUE TITLE
example for log plot with ptable_heatmap_plotly

### ISSUE THREAD

**Issue by sgbaird** [janosh/pymatviz#52]
Not a huge priority rn. I'll use `ptable_heatmap` for now, instead.

Some resources:
- https://plotly.com/python/colorscales/#customizing-tick-text-on-logarithmic-color-bars
- https://github.com/plotly/documentation/issues/1611

I might circle back to this later and flesh out an example if I need a plotly heatmap table that has log scaling and hover information.

**Comment by janosh** [comment]
I've been meaning to do that for a while. Iirc, I looked into this a while back and the only annoying bit was getting the color bar tick positions and labels right in a robust way. I'll whip something up. Not sure how robust it'll be. 😅

**Comment by janosh** [comment]
Released in [v0.5.0](https://github.com/janosh/pymatviz/releases/tag/v0.5.0).
