### ISSUE TITLE
Changing the edge color of atoms 

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [janosh/pymatviz#71]
Using `from pymatviz import plot_structure_2d`, we can plot atoms, but is there a way to change the edge or face color of the atoms using the attributes of `plot_structure_2d()`? In the source code, `Wedge()` is already defined with edge color. Further, there is no option for `xlabel` or `ylabel` when I set them?

**Comment by janosh** [comment]
Bear in mind that the edge drawing functionality in `plot_structure_2d()` is still experimental.

https://github.com/janosh/pymatviz/blob/05368c034f6c2aff572011b93c5b4c722ee7559b/pymatviz/structure_viz.py#L347-L352

Even though it's not well tested, I think the functionality you're asking about is already there. Have a look at the doc string. Specifically `colors`, `show_bonds` and `bond_kwargs`.

https://github.com/janosh/pymatviz/blob/05368c034f6c2aff572011b93c5b4c722ee7559b/pymatviz/structure_viz.py#L166-L186

Here's a code snippet showing how to use them taken from [`_generate_assets.py`](https://github.com/janosh/pymatviz/blob/05368c034f6c2aff572011b93c5b4c722ee7559b/assets/_generate_assets.py#L243-L253):

```py
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matminer.datasets import load_dataset

df_phonons = load_dataset("matbench_phonons")

df_phonons[["spg_symbol", "spg_num"]] = [
    struct.get_space_group_info() for struct in tqdm(df_phonons.structure)
]

n_rows, n_cols = 3, 4
fig, axs = plt.subplots(n_rows, n_cols, figsize=(3 * n_cols, 3 * n_rows))
title = f"{len(axs.flat)} Matbench Phonons Structures"
fig.suptitle(title, fontweight="bold", fontsize=20)

for row, ax in zip(df_phonons.itertuples(), axs.flat):
    idx, struct, *_, spg_num = row
    plot_structure_2d(
        struct,
        ax=ax,
        show_bonds=True,
        bond_kwargs=dict(facecolor="gray", linewidth=2, linestyle="dotted", alpha=0.5),
    )
    sub_title = f"{idx + 1}. {struct.formula} ({spg_num})"
    ax.set_title(sub_title, fontweight="bold")
```

![matbench-phonons-structures-2d](https://user-images.githubusercontent.com/30958850/226421982-75aa2859-13ca-4e16-bb7d-0db0d3b9d47d.svg)

I'm not sure what you mean by x/y-label on a structure. Does the subplot title above each structure in the figure above serve your purpose?

**Comment by janosh** [comment]
That's because of https://github.com/janosh/pymatviz/blob/05368c034f6c2aff572011b93c5b4c722ee7559b/pymatviz/structure_viz.py#L401

We can add a kwarg

```py
axis: Literal[
  "on", "off", "equal", "scaled", "tight", "auto", "image", "square"
] = "off",
```

to disable turning off the plot's axes. Then you'd get sth like this. Is that what you're after?

![matbench-phonons-structures-2d](https://user-images.githubusercontent.com/30958850/226439724-ca820699-fcfa-4766-afb6-d904d319de1b.svg)

**Comment by Asif-Iqbal-Bhatti** [comment]
Yes that is what I want. The reason for this is that when looking at the crystal along the [111] (bcc screw dislocations), the distortion of the surface atoms should be clearly visible on a 2D graph. We can measure how much there is deviation from the unrelax position after doping with alloy elements. In this way we can highlight the atoms and change the radius to see distortion. SO I have to add this 
axis: Literal[
  "on", "off", "equal", "scaled", "tight", "auto", "image", "square"
] = "off",
in 
plot_structure_2d(struct, ax[0], rotation='0x,0y,0z',
                    atomic_radii={'H':0.05, 'Fe':0.2}, 
                    colors={'H':'k','Fe':'b'},
                    show_unit_cell=True, site_labels=False,
                    label_kwargs={"fontsize": 4,},
                    kwarg = {'axes': "off"},)

Again thank you for this. I must say this function is very useful if our workflow involves automation.

**Comment by janosh** [comment]
Thanks for giving some context.

If you're looking to visualize structure relaxations, this could also be relevant for you: https://github.com/materialsproject/crystaltoolkit/pull/323

CrystalToolkit has the advantage of rendering structures in 3d. For automation purposes, you can take any browser tool like Puppeteer to take snapshots. I'm not sure about this but I think CrystalToolkit might even have snapshot functionality built in.
